<br/><br/><br/><br/><br/>
<font size=6>**Introduction to Working with U.S. Census Data in Python, Part III**</font>
<br/>
<font size=5>**PyData Seattle 2023**
<br/>
[**Darren Erik Vengroff, Ph.D.**](https://www.linkedin.com/in/vengroff/)
<br/>
April 23, 2023
</font>
<br/><br/><br/><br/>
<font size=6>**Exercise / Project Template**</font>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

## Exercise / Project Template

This is an open-ended template that you can use to start
your own U.S. Census data research project building on
what you learned today.

It is a skeleton you can fill in to create your first 
full-blown Census-data-based research project.

## Getting Started

If you want to run this notebook yourself, we encourage you
to do so in whatever virtual environment you normally do your
work. It could be in an IDE like [VSCode](https://code.visualstudio.com/docs/datascience/jupyter-notebooks)
or a hosted notebook
environment like [google colab](https://colab.research.google.com/).
The only thing you have to do is `pip install censusdis`, or the
equivalent in your environment. Then you should be able to run
this notebook and whatever notebook(s) you derive from it.

## Resources

We encourage you to refer back to the two other notebooks we 
went through during the tutorial for tips, ideas, and code
you can copy and modify.

You can also look through the numerous sample notebooks at 
https://github.com/vengroff/censusdis/tree/main/notebooks.

## Imports

Here are some basic imports you are likely to need in your
work. You may want to adjust what state or states you import
in case you are focused on a different area.

In [1]:
import censusdis.data as ced
import censusdis.maps as cem
from censusdis.states import NJ


import pandas as pd

# Some of the names of variables get really long.
# This option ensures they are readable in the notebook.
pd.set_option('display.max_colwidth', 200)

## What is your research question?

As we did in our earlier notebooks, we'd like to formulate
the question as something along the lines of:

- What is/are the value of **\[demographic, economic, political, ... variable(s) \]** in **\[geographic location(s)\]**?

Examples we studied earlier were:

- What is the **median income** in **counties in Washington State**?
- How many **children under the age of 18 live in poverty** in **each census tract in Newark, NJ**?

Fill in the blanks below to formulate your own research question:

## My research question is:

What is/how many/how much _________________________ 
in _________________________?

## Find a group of variables related to you research question

In [2]:
DATASET = 'acs/acs5'
VINTAGE = 2020

In [3]:
df_groups = ced.variables.all_groups(DATASET, VINTAGE)

In [4]:
# Change the query here as needed to find a group or group
# of variables that interest you.

# In this example, we are interested in insurance and want
# to know how age affects coverage, and we are specifically
# interested in women. You should change this to keywords 
# relevant to your project.
df_groups[
    df_groups['DESCRIPTION'].str.contains('INSURANCE') &
    df_groups['DESCRIPTION'].str.contains('SEX') &
    df_groups['DESCRIPTION'].str.contains('AGE')
]

,DATASET,YEAR,GROUP,DESCRIPTION
910,acs/acs5,2020,B27001,HEALTH INSURANCE COVERAGE STATUS BY SEX BY AGE
911,acs/acs5,2020,B27002,PRIVATE HEALTH INSURANCE STATUS BY SEX BY AGE
912,acs/acs5,2020,B27003,PUBLIC HEALTH INSURANCE STATUS BY SEX BY AGE
918,acs/acs5,2020,B27022,HEALTH INSURANCE COVERAGE STATUS BY SEX BY ENROLLMENT STATUS FOR YOUNG ADULTS AGED 19 TO 25
919,acs/acs5,2020,B27023,PRIVATE HEALTH INSURANCE BY SEX BY ENROLLMENT STATUS FOR YOUNG ADULTS AGED 19 TO 25
1127,acs/acs5,2020,C27004,EMPLOYER-BASED HEALTH INSURANCE BY SEX BY AGE
1128,acs/acs5,2020,C27005,DIRECT-PURCHASE HEALTH INSURANCE BY SEX BY AGE

In [5]:
# This is the group we picked from the options we found
# above.
GROUP = 'B27001'

## Decide what variables we want to use

Look at the variables in your group, which ones are
leaves, and decide which are relevant to your research
question. You might want a subset of the leaves, like
we did in the Newark case study. You might want all the
leaves, or you might want all the variables.

One or more of the `ced.variables.*` queries in the following
few cells might help you find the variable(s) you want.

In [6]:
ced.variables.all_variables(DATASET, VINTAGE, GROUP)

,YEAR,DATASET,GROUP,VARIABLE,LABEL,SUGGESTED_WEIGHT,VALUES
0,2020,acs/acs5,B27001,B27001_001E,Estimate!!Total:,NaN,None
1,2020,acs/acs5,B27001,B27001_002E,Estimate!!Total:!!Male:,NaN,None
2,2020,acs/acs5,B27001,B27001_003E,Estimate!!Total:!!Male:!!Under 6 years:,NaN,None
3,2020,acs/acs5,B27001,B27001_004E,Estimate!!Total:!!Male:!!Under 6 years:!!With health insurance coverage,NaN,None
4,2020,acs/acs5,B27001,B27001_005E,Estimate!!Total:!!Male:!!Under 6 years:!!No health insurance coverage,NaN,None
5,2020,acs/acs5,B27001,B27001_006E,Estimate!!Total:!!Male:!!6 to 18 years:,NaN,None
6,2020,acs/acs5,B27001,B27001_007E,Estimate!!Total:!!Male:!!6 to 18 years:!!With health insurance coverage,NaN,None
7,2020,acs/acs5,B27001,B27001_008E,Estimate!!Total:!!Male:!!6 to 18 years:!!No health insurance coverage,NaN,None
8,2020,acs/acs5,B27001,B27001_009E,Estimate!!Total:!!Male:!!19 to 25 years:,NaN,None
9,2020,acs/acs5,B27001,B27001_010E,Estimate!!Total:!!Male:!!19 to 25 years:!!With health insurance coverage,NaN,None
10,2020,acs/acs5,B27001,B27001_011E,Estimate!!Total:!!Male:!!19 to 25 years:!!No health insurance coverage,NaN,None
11,2020,acs/acs5,B27001,B27001_012E,Estimate!!Total:!!Male:!!26 to 34 years:,NaN,None
12,2020,acs/acs5,B27001,B27001_013E,Estimate!!Total:!!Male:!!26 to 34 years:!!With health insurance coverage,NaN,None
13,2020,acs/acs5,B27001,B27001_014E,Estimate!!Total:!!Male:!!26 to 34 years:!!No health insurance coverage,NaN,None
14,2020,acs/acs5,B27001,B27001_015E,Estimate!!Total:!!Male:!!35 to 44 years:,NaN,None
15,2020,acs/acs5,B27001,B27001_016E,Estimate!!Total:!!Male:!!35 to 44 years:!!With health insurance coverage,NaN,None
16,2020,acs/acs5,B27001,B27001_017E,Estimate!!Total:!!Male:!!35 to 44 years:!!No health insurance coverage,NaN,None
17,2020,acs/acs5,B27001,B27001_018E,Estimate!!Total:!!Male:!!45 to 54 years:,NaN,None
18,2020,acs/acs5,B27001,B27001_019E,Estimate!!Total:!!Male:!!45 to 54 years:!!With health insurance coverage,NaN,None
19,2020,acs/acs5,B27001,B27001_020E,Estimate!!Total:!!Male:!!45 to 54 years:!!No health insurance coverage,NaN,None
20,2020,acs/acs5,B27001,B27001_021E,Estimate!!Total:!!Male:!!55 to 64 years:,NaN,None
21,2020,acs/acs5,B27001,B27001_022E,Estimate!!Total:!!Male:!!55 to 64 years:!!With health insurance coverage,NaN,None
22,2020,acs/acs5,B27001,B27001_023E,Estimate!!Total:!!Male:!!55 to 64 years:!!No health insurance coverage,NaN,None
23,2020,acs/acs5,B27001,B27001_024E,Estimate!!Total:!!Male:!!65 to 74 years:,NaN,None
24,2020,acs/acs5,B27001,B27001_025E,Estimate!!Total:!!Male:!!65 to 74 years:!!With health insurance coverage,NaN,None
25,2020,acs/acs5,B27001,B27001_026E,Estimate!!Total:!!Male:!!65 to 74 years:!!No health insurance coverage,NaN,None
26,2020,acs/acs5,B27001,B27001_027E,Estimate!!Total:!!Male:!!75 years and over:,NaN,None
27,2020,acs/acs5,B27001,B27001_028E,Estimate!!Total:!!Male:!!75 years and over:!!With health insurance coverage,NaN,None
28,2020,acs/acs5,B27001,B27001_029E,Estimate!!Total:!!Male:!!75 years and over:!!No health insurance coverage,NaN,None
29,2020,acs/acs5,B27001,B27001_030E,Estimate!!Total:!!Female:,NaN,None
30,2020,acs/acs5,B27001,B27001_031E,Estimate!!Total:!!Female:!!Under 6 years:,NaN,None
31,2020,acs/acs5,B27001,B27001_032E,Estimate!!Total:!!Female:!!Under 6 years:!!With health insurance coverage,NaN,None
32,2020,acs/acs5,B27001,B27001_033E,Estimate!!Total:!!Female:!!Under 6 years:!!No health insurance coverage,NaN,None
33,2020,acs/acs5,B27001,B27001_034E,Estimate!!Total:!!Female:!!6 to 18 years:,NaN,None
34,2020,acs/acs5,B27001,B27001_035E,Estimate!!Total:!!Female:!!6 to 18 years:!!With health insurance coverage,NaN,None
35,2020,acs/acs5,B27001,B27001_036E,Estimate!!Total:!!Female:!!6 to 18 years:!!No health insurance coverage,NaN,None
36,2020,acs/acs5,B27001,B27001_037E,Estimate!!Total:!!Female:!!19 to 25 years:,NaN,None
37,2020,acs/acs5,B27001,B27001_038E,Estimate!!Total:!!Female:!!19 to 25 years:!!With health insurance coverage,NaN,None
38,2020,acs/acs5,B27001,B27001_039E,Estimate!!Total:!!Female:!!19 to 25 years:!!No health insurance coverage,NaN,None
39,2020,acs/acs5,B27001,B27001_040E,Estimate!!Total:!!Female:!!26 to 34 years:,NaN,None
40,2020,acs/acs5,B27001,B27001_041E,Estimate!!Total:!!Female:!!26 to 34 years:!!With health insurance coverage,NaN,None
41,2020,acs/acs5,B27001,B27001_042E,Estimate!!Total:!!Female:!!26 to 34 years:!!No health insurance coverage,NaN,None
42,2020,acs/acs5,B27001,B27001_043E,Estimate!!Total:!!Female:!!35 to 44 years:,NaN,None
43,2020,acs/acs5,B27001,B27001_044E,Estimate!!Total:!!Female:!!35 to 44 years:!!With health insurance coverage,NaN,None
44,2020,acs/acs5,B27001,B27001_045E,Estimate!!Total:!!Female:!!35 to 44 years:!!No health insurance coverage,NaN,None
45,2020,acs/acs5,B27001,B27001_046E,Estimate!!Total:!!Female:!!45 to 54 years:,NaN,None
46,2020,acs/acs5,B27001,B27001_047E,Estimate!!Total:!!Female:!!45 to 54 years:!!With health insurance coverage,NaN,None
47,2020,acs/acs5,B27001,B27001_048E,Estimate!!Total:!!Female:!!45 to 54 years:!!No health insurance coverage,NaN,None
48,2020,acs/acs5,B27001,B27001_049E,Estimate!!Total:!!Female:!!55 to 64 years:,NaN,None
49,2020,acs/acs5,B27001,B27001_050E,Estimate!!Total:!!Female:!!55 to 64 years:!!With health insurance coverage,NaN,None
50,2020,acs/acs5,B27001,B27001_051E,Estimate!!Total:!!Female:!!55 to 64 years:!!No health insurance coverage,NaN,None
51,2020,acs/acs5,B27001,B27001_052E,Estimate!!Total:!!Female:!!65 to 74 years:,NaN,None
52,2020,acs/acs5,B27001,B27001_053E,Estimate!!Total:!!Female:!!65 to 74 years:!!With health insurance coverage,NaN,None
53,2020,acs/acs5,B27001,B27001_054E,Estimate!!Total:!!Female:!!65 to 74 years:!!No health insurance coverage,NaN,None
54,2020,acs/acs5,B27001,B27001_055E,Estimate!!Total:!!Female:!!75 years and over:,NaN,None
55,2020,acs/acs5,B27001,B27001_056E,Estimate!!Total:!!Female:!!75 years and over:!!With health insurance coverage,NaN,None
56,2020,acs/acs5,B27001,B27001_057E,Estimate!!Total:!!Female:!!75 years and over:!!No health insurance coverage,NaN,None

In [7]:
ced.variables.group_tree(DATASET, VINTAGE, GROUP)

+ Estimate
    + Total: (B27001_001E)
        + Male: (B27001_002E)
            + Under 6 years: (B27001_003E)
                + With health insurance coverage (B27001_004E)
                + No health insurance coverage (B27001_005E)
            + 6 to 18 years: (B27001_006E)
                + With health insurance coverage (B27001_007E)
                + No health insurance coverage (B27001_008E)
            + 19 to 25 years: (B27001_009E)
                + With health insurance coverage (B27001_010E)
                + No health insurance coverage (B27001_011E)
            + 26 to 34 years: (B27001_012E)
                + With health insurance coverage (B27001_013E)
                + No health insurance coverage (B27001_014E)
            + 35 to 44 years: (B27001_015E)
                + With health insurance coverage (B27001_016E)
                + No health insurance coverage (B27001_017E)
            + 45 to 54 years: (B27001_018E)
                + With health insurance coverage (B27001_019E)
                + No health insurance coverage (B27001_020E)
            + 55 to 64 years: (B27001_021E)
                + With health insurance coverage (B27001_022E)
                + No health insurance coverage (B27001_023E)
            + 65 to 74 years: (B27001_024E)
                + With health insurance coverage (B27001_025E)
                + No health insurance coverage (B27001_026E)
            + 75 years and over: (B27001_027E)
                + With health insurance coverage (B27001_028E)
                + No health insurance coverage (B27001_029E)
        + Female: (B27001_030E)
            + Under 6 years: (B27001_031E)
                + With health insurance coverage (B27001_032E)
                + No health insurance coverage (B27001_033E)
            + 6 to 18 years: (B27001_034E)
                + With health insurance coverage (B27001_035E)
                + No health insurance coverage (B27001_036E)
            + 19 to 25 years: (B27001_037E)
                + With health insurance coverage (B27001_038E)
                + No health insurance coverage (B27001_039E)
            + 26 to 34 years: (B27001_040E)
                + With health insurance coverage (B27001_041E)
                + No health insurance coverage (B27001_042E)
            + 35 to 44 years: (B27001_043E)
                + With health insurance coverage (B27001_044E)
                + No health insurance coverage (B27001_045E)
            + 45 to 54 years: (B27001_046E)
                + With health insurance coverage (B27001_047E)
                + No health insurance coverage (B27001_048E)
            + 55 to 64 years: (B27001_049E)
                + With health insurance coverage (B27001_050E)
                + No health insurance coverage (B27001_051E)
            + 65 to 74 years: (B27001_052E)
                + With health insurance coverage (B27001_053E)
                + No health insurance coverage (B27001_054E)
            + 75 years and over: (B27001_055E)
                + With health insurance coverage (B27001_056E)
                + No health insurance coverage (B27001_057E)

In [8]:
ced.variables.group_leaves(DATASET, VINTAGE, GROUP)

['B27001_004E',
 'B27001_005E',
 'B27001_007E',
 'B27001_008E',
 'B27001_010E',
 'B27001_011E',
 'B27001_013E',
 'B27001_014E',
 'B27001_016E',
 'B27001_017E',
 'B27001_019E',
 'B27001_020E',
 'B27001_022E',
 'B27001_023E',
 'B27001_025E',
 'B27001_026E',
 'B27001_028E',
 'B27001_029E',
 'B27001_032E',
 'B27001_033E',
 'B27001_035E',
 'B27001_036E',
 'B27001_038E',
 'B27001_039E',
 'B27001_041E',
 'B27001_042E',
 'B27001_044E',
 'B27001_045E',
 'B27001_047E',
 'B27001_048E',
 'B27001_050E',
 'B27001_051E',
 'B27001_053E',
 'B27001_054E',
 'B27001_056E',
 'B27001_057E']

In [9]:
# Chose the right set of variables for your 
# particular research question. In this case,
# looking through the variables, leaves, and
# tree above, we came up with this formulation
# for the variables we want. Some times it's easy
# to define a set of variables like this. In other
# cases we might just hard-code variables like we
# did in the Newark example.

variables = [
    leaf
    for leaf in ced.variables.group_leaves(DATASET, VINTAGE, GROUP)
    if leaf > 'B27001_030E'
]
variables

['B27001_032E',
 'B27001_033E',
 'B27001_035E',
 'B27001_036E',
 'B27001_038E',
 'B27001_039E',
 'B27001_041E',
 'B27001_042E',
 'B27001_044E',
 'B27001_045E',
 'B27001_047E',
 'B27001_048E',
 'B27001_050E',
 'B27001_051E',
 'B27001_053E',
 'B27001_054E',
 'B27001_056E',
 'B27001_057E']

## Choose a geography

Now we have to choose what geographies we want to study.
This first query tells us all possible geographies.

In [10]:
list(ced.geographies(DATASET, VINTAGE))

[['us'],
 ['region'],
 ['division'],
 ['state'],
 ['state', 'county'],
 ['state', 'county', 'county_subdivision'],
 ['state', 'county', 'county_subdivision', 'subminor_civil_division'],
 ['state', 'county', 'county_subdivision', 'place_remainder_or_part'],
 ['state', 'county', 'tract'],
 ['state', 'county', 'tract', 'block_group'],
 ['state', 'place', 'county_or_part'],
 ['state', 'place'],
 ['state', 'consolidated_city'],
 ['state', 'consolidated_city', 'place_or_part'],
 ['state', 'alaska_native_regional_corporation'],
 ['american_indian_area_alaska_native_area_hawaiian_home_land'],
 ['american_indian_area_alaska_native_area_hawaiian_home_land',
  'tribal_subdivision_remainder'],
 ['american_indian_area_alaska_native_area_reservation_or_statistical_entity_only'],
 ['american_indian_area_off_reservation_trust_land_only_hawaiian_home_land'],
 ['american_indian_area_alaska_native_area_hawaiian_home_land',
  'tribal_census_tract'],
 ['american_indian_area_alaska_native_area_hawaiian_home_land',
  'tribal_census_tract',
  'tribal_block_group'],
 ['american_indian_area_alaska_native_area_hawaiian_home_land',
  'state_or_part'],
 ['american_indian_area_alaska_native_area_hawaiian_home_land',
  'state_or_part',
  'place_remainder_or_part'],
 ['american_indian_area_alaska_native_area_hawaiian_home_land',
  'state_or_part',
  'county_or_part'],
 ['state',
  'american_indian_area_alaska_native_area_hawaiian_home_land_or_part'],
 ['state',
  'american_indian_area_alaska_native_area_reservation_or_statistical_entity_only_or_part'],
 ['state',
  'american_indian_area_off_reservation_trust_land_only_hawaiian_home_land_or_part'],
 ['american_indian_area_alaska_native_area_hawaiian_home_land',
  'tribal_subdivision_remainder',
  'state_or_part'],
 ['american_indian_area_reservation_only', 'tribal_census_tract_or_part'],
 ['american_indian_area_off_reservation_trust_land_only_hawaiian_home_land',
  'tribal_census_tract_or_part'],
 ['american_indian_area_reservation_only',
  'tribal_census_tract_or_part',
  'tribal_block_group_or_part'],
 ['american_indian_area_off_reservation_trust_land_only_hawaiian_home_land',
  'tribal_census_tract_or_part',
  'tribal_block_group_or_part'],
 ['metropolitan_statistical_area_micropolitan_statistical_area'],
 ['metropolitan_statistical_area_micropolitan_statistical_area',
  'state_or_part'],
 ['metropolitan_statistical_area_micropolitan_statistical_area',
  'state_or_part',
  'principal_city_or_part'],
 ['metropolitan_statistical_area_micropolitan_statistical_area',
  'state_or_part',
  'county'],
 ['metropolitan_statistical_area_micropolitan_statistical_area',
  'metropolitan_division'],
 ['metropolitan_statistical_area_micropolitan_statistical_area',
  'metropolitan_division',
  'state_or_part'],
 ['metropolitan_statistical_area_micropolitan_statistical_area',
  'metropolitan_division',
  'state_or_part',
  'county'],
 ['state',
  'metropolitan_statistical_area_micropolitan_statistical_area_or_part'],
 ['state',
  'metropolitan_statistical_area_micropolitan_statistical_area_or_part',
  'principal_city_or_part'],
 ['state',
  'metropolitan_statistical_area_micropolitan_statistical_area_or_part',
  'county'],
 ['state',
  'metropolitan_statistical_area_micropolitan_statistical_area_or_part',
  'metropolitan_division_or_part'],
 ['state',
  'metropolitan_statistical_area_micropolitan_statistical_area_or_part',
  'metropolitan_division_or_part',
  'county'],
 ['combined_statistical_area'],
 ['combined_statistical_area', 'state_or_part'],
 ['combined_statistical_area',
  'metropolitan_statistical_area_micropolitan_statistical_area'],
 ['combined_statistical_area',
  'metropolitan_statistical_area_micropolitan_statistical_area',
  'state_or_part'],
 ['combined_new_england_city_and_town_area'],
 ['combined_new_england_city_and_town_area', 'state_or_part'],
 ['combined_new_england_city_and_town_area', 'new_england_city_and_town_area'],
 ['combined_new_england_city_and_town_area',
  'new_england_city_and_town_area',
  'state_or_part'],
 ['state', 'combined_statistical_area_or_part'],
 ['state',
  'combined_statistical_area_or_part',
  'metropolitan_statistical_area_micropolitan_statistical_area_or_part'],
 ['state', 'combined_new_england_city_and_town_area_or_part'],
 ['state',
  'combined_new_england_city_and_town_area_or_part',
  'new_england_city_and_town_area_or_part'],
 ['new_england_city_and_town_area'],
 ['new_england_city_and_town_area', 'state_or_part'],
 ['new_england_city_and_town_area', 'state_or_part', 'principal_city'],
 ['new_england_city_and_town_area', 'state_or_part', 'county_or_part'],
 ['new_england_city_and_town_area',
  'state_or_part',
  'county_or_part',
  'county_subdivision'],
 ['new_england_city_and_town_area', 'necta_division'],
 ['new_england_city_and_town_area', 'necta_division', 'state_or_part'],
 ['new_england_city_and_town_area',
  'necta_division',
  'state_or_part',
  'county_or_part'],
 ['new_england_city_and_town_area',
  'necta_division',
  'state_or_part',
  'county_or_part',
  'county_subdivision'],
 ['state', 'new_england_city_and_town_area_or_part'],
 ['state', 'new_england_city_and_town_area_or_part', 'principal_city'],
 ['state', 'new_england_city_and_town_area_or_part', 'county_or_part'],
 ['state',
  'new_england_city_and_town_area_or_part',
  'county_or_part',
  'county_subdivision'],
 ['state', 'new_england_city_and_town_area_or_part', 'necta_division_or_part'],
 ['state',
  'new_england_city_and_town_area_or_part',
  'necta_division_or_part',
  'county_or_part'],
 ['state',
  'new_england_city_and_town_area_or_part',
  'necta_division_or_part',
  'county_or_part',
  'county_subdivision'],
 ['urban_area'],
 ['urban_area', 'state'],
 ['urban_area', 'state', 'county'],
 ['state', 'congressional_district'],
 ['state', 'congressional_district', 'county_or_part'],
 ['state',
  'congressional_district',
  'american_indian_area_alaska_native_area_hawaiian_home_land_or_part'],
 ['state', 'state_legislative_district_upper_chamber'],
 ['state', 'state_legislative_district_upper_chamber', 'county_or_part'],
 ['state', 'state_legislative_district_lower_chamber'],
 ['state', 'state_legislative_district_lower_chamber', 'county_or_part'],
 ['state', 'public_use_microdata_area'],
 ['zip_code_tabulation_area'],
 ['state', 'school_district_elementary'],
 ['state', 'school_district_secondary'],
 ['state', 'school_district_unified']]

In our hypothethical example, let's suppose we want
nationwide data at the county level. So when we make
our queries we'll use `state='*', county='*'` to get
all counties in all states.

In [11]:
df_data = ced.download(
    DATASET,
    VINTAGE,
    ['NAME'] + variables,
    
    state='*',
    county='*',
)

In [12]:
df_data.head()

,STATE,COUNTY,NAME,B27001_032E,B27001_033E,B27001_035E,B27001_036E,B27001_038E,B27001_039E,B27001_041E,...,B27001_044E,B27001_045E,B27001_047E,B27001_048E,B27001_050E,B27001_051E,B27001_053E,B27001_054E,B27001_056E,B27001_057E
0,01,001,"Autauga County, Alabama",1722,40,4869,154,1867,368,2781,...,3321,458,3615,229,3292,408,2741,0,1962,0
1,01,003,"Baldwin County, Alabama",6898,92,16236,912,6585,1484,8777,...,11685,1910,12930,1806,15240,1344,14160,49,9495,44
2,01,005,"Barbour County, Alabama",768,33,1909,16,748,62,954,...,997,266,1238,164,1401,177,1554,0,1069,5
3,01,007,"Bibb County, Alabama",632,35,1518,11,581,161,908,...,1271,182,1248,145,1249,122,1098,0,871,0
4,01,009,"Blount County, Alabama",1978,68,4585,120,1741,498,2472,...,2999,516,3149,682,3612,253,3126,11,2437,19

In [13]:
df_data.describe()

,B27001_032E,B27001_033E,B27001_035E,B27001_036E,B27001_038E,B27001_039E,B27001_041E,B27001_042E,B27001_044E,B27001_045E,B27001_047E,B27001_048E,B27001_050E,B27001_051E,B27001_053E,B27001_054E,B27001_056E,B27001_057E
count,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000,3221.000000
mean,3441.364483,152.924558,7844.379385,458.315120,4070.364483,581.887302,5460.306427,801.670910,5720.788885,747.623409,5931.155231,652.301459,6282.973300,522.610680,5021.130705,48.912760,3802.881093,22.090966
std,11452.706897,590.955155,25039.306764,1954.356907,13563.194951,2375.097649,19877.765077,3282.675761,19360.338902,3196.354296,19203.124817,2687.532528,18818.994014,1877.528071,14324.278357,265.800399,11351.716189,127.667832
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,329.000000,6.000000,819.000000,35.000000,307.000000,42.000000,428.000000,60.000000,507.000000,62.000000,565.000000,61.000000,722.000000,59.000000,633.000000,0.000000,488.000000,0.000000
50%,815.000000,34.000000,1967.000000,110.000000,850.000000,133.000000,1110.000000,175.000000,1277.000000,169.000000,1419.000000,164.000000,1700.000000,150.000000,1451.000000,0.000000,1101.000000,0.000000
75%,2173.000000,108.000000,5155.000000,312.000000,2458.000000,377.000000,3050.000000,494.000000,3423.000000,448.000000,3805.000000,425.000000,4405.000000,386.000000,3733.000000,18.000000,2703.000000,6.000000
max,335579.000000,18930.000000,750922.000000,63641.000000,442846.000000,68045.000000,626637.000000,92031.000000,602248.000000,88573.000000,598306.000000,76036.000000,567687.000000,50533.000000,413545.000000,7301.000000,335010.000000,3714.000000

## Analysis

At this point we have the U.S. Census data we want. It's in an
ordinary data frame, so we can do whatever analysis we need
to to answer our research question.

Assuming you made appropriate changes to the cells above to
locate the variables you want and query them for the geographies
you want, you are ready to move forward.

Good luck, both here and in your future work with U.S. Census data
in Python.